[package]
name = "pigeon-server"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
actix = "0.13.3"
