[workspace]
members = ["crates/pigeon-pingora", "crates/pigeon-server"]
default-members = ["crates/pigeon-server"]
resolver = "2"

[workspace.package]
version = "0.1.0"
description = "A game server framework supporting hot-reload."
authors = ["EvanLuo42"]
edition = "2021"
