[package]
name = "pigeon-logic"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
actix = { workspace = true }
actix-rt = { workspace = true }
bytes = { workspace = true }
