[package]
name = "pigeon-gateway"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
pigeon-auth = { path = "../pigeon-auth" }
